In [ ]:
# 과제3: Carly's Clippers

In [40]:
import numpy as np

In [84]:
hairstyles = np.array(["bouffant", "pixie", "dreadlocks", "crew", "bowl", "bob", "mohawk", "flattop"])
print(hairstyles)

['bouffant' 'pixie' 'dreadlocks' 'crew' 'bowl' 'bob' 'mohawk' 'flattop']


In [85]:
prices = np.array([30, 25, 40, 20, 20, 35, 50, 35])
print(prices)

[30 25 40 20 20 35 50 35]


In [86]:
last_week = np.array([2, 3, 5, 8, 4, 4, 6, 2])
print(last_week)

[2 3 5 8 4 4 6 2]


In [87]:
total_price = 0
print(total_price)

0


In [88]:
total_price = np.add.reduce(prices)
print(total_price)

255


In [89]:
average_price = total_price / len(prices)

In [90]:
print("Average price is %.3f" %(average_price))

Average price is 31.875


In [91]:
new_prices = prices - 5

In [92]:
print(new_prices)

[25 20 35 15 15 30 45 30]


In [93]:
total_revenue = 0
print(total_revenue)

0


In [94]:
for i in range(len(hairstyles)):
    total_revenue = total_revenue + (prices[i] * last_week[i])

In [95]:
print(total_revenue)

1085


In [96]:
average_daily_revenue = total_revenue / 7
print("Average daily revenue is %.1f" %(average_daily_revenue))

Average daily revenue is 155.0


In [97]:
cut_under_30 = [hairstyles[i] for i in range(len(new_prices) - 1) if new_prices[i] < 30]

In [98]:
print(cut_under_30)

['bouffant', 'pixie', 'crew', 'bowl']
